name:  Deploy MERN Chat App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04 [Beta]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --- FRONTEND BUILD ----
      - name: setup Node for web
        uses: actions/setup-node@v4
        with:
            node-version: "22"

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # --- Bacend Test + Prepare
      - name: Install backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm run test

      # -- Deploy To EC2 ---
      - name: Copy Files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "home/ubuntu/mern-chat-app"

      - name: Execute Remote SSH command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
              cd /home/ubuntu/mern-chat-app/backend
              npm ci 
              pm2 stop all 
              pm2 start src/index.js --name chat-backend 
            
              cd /home/ubuntu/mern-chat-app/frontend
              sudo rm -rf /var/ww/chatapp/*
              sudo cp -r dist/* /var/www/chat-app/ 
            
              sudo systemctl restart nginx

